## NUMPY

In [1]:
#numpy installation
!pip install numpy

In [2]:
import numpy as np

## Array

In [3]:
arr1=np.array([1,2,3,80])
print(arr1)

[ 1  2  3 80]


In [4]:
print(type(arr1))


<class 'numpy.ndarray'>


In [5]:
#1D ARRAY
array2=np.array((1,6,8,3))
print(array2)

[1 6 8 3]


In [7]:
print(np.shape(array2)) # returns shape (rows, col)
print(np.ndim(array2)) #return number of dimentions
print(np.size(array2)) #returns num of all elements of array'

(4,)
1
4


In [10]:
#2D ARRAY
array3=np.array([[1,6],[5,9],[5,7]])
print(array3)

[[1 6]
 [5 9]
 [5 7]]


In [11]:
print(np.shape(array3)) # returns shape (rows, col)
print(np.ndim(array3)) #return number of dimentions
print(np.size(array3)) #returns num of all elements of array'

(3, 2)
2
6


In [12]:
#3D ARRAY
array3=np.array([
    [[34,67],[45,78]],
    [[23,67],[45,90]]])
print(array3)

[[[34 67]
  [45 78]]

 [[23 67]
  [45 90]]]


In [14]:
print("shape: ", np.shape(array3)) # returns shape (rows, col)
print("dimention :", np.ndim(array3)) #return number of dimentions
print("size :", np.size(array3)) #returns num of all elements of array'

shape:  (2, 2, 2)
dimention : 3
size : 8


In [16]:
#4D ARRAY
array4=np.arange(16).reshape(2,2,2,2)
print(array4)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [17]:
print("shape: ", np.shape(array4)) # returns shape (rows, col)
print("dimention :", np.ndim(array4)) #return number of dimentions
print("size :", np.size(array4)) #returns num of all elements of array'

shape:  (2, 2, 2, 2)
dimention : 4
size : 16


# Note:
1️⃣ np.arange(16)
np.arange(n) creates an array of integers from 0 to n-1.
So np.arange(16) gives:

o/p : array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

2️⃣ .reshape(2,2,2,2)
reshape changes the shape of an array without changing its data.
(2,2,2,2) means a 4-dimensional array:
1st dimension: 2 blocks
2nd dimension: 2 sub-blocks in each block
3rd dimension: 2 rows in each sub-block
4th dimension: 2 columns in each row

In [ ]:
array function: arrange, linspace, random number generation, seed, reshape, ravel.
    

1️⃣ np.arange()
Purpose: Create a 1D array with evenly spaced values.
Syntax: np.arange(start, stop, step)

2️⃣ np.linspace()
Purpose: Create an array with a specific number of evenly spaced values between two endpoints.
Syntax: np.linspace(start, stop, num)

3️⃣ Random Number Generation (np.random)
Purpose: Generate random numbers (integers or floats).



In [18]:
import numpy as np

a = np.arange(0, 10, 2)  # start=0, stop=10 (exclusive), step=2
print(a)  # Output: [0 2 4 6 8]


[0 2 4 6 8]


In [19]:
b = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
print(b)  # Output: [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


In [20]:
# Random float numbers between 0 and 1
rand_floats = np.random.rand(3)  
print(rand_floats)  # Example: [0.5488135  0.71518937 0.60276338]

# Random integers
rand_ints = np.random.randint(1, 10, size=5)  # 5 integers from 1 to 9
print(rand_ints)  # Example: [3 7 1 9 2]


[0.97135921 0.48815135 0.96370037]
[2 4 1 5 7]


In [21]:
np.random.seed(42)
print(np.random.rand(3))  # Always the same output: [0.37454012 0.95071431 0.73199394]


[0.37454012 0.95071431 0.73199394]
